# tell docker what version of the docker-compose.yml we're using
version: '3'

# define the network
# 定义网络
networks:
  web-app-network:

services:
  docker-eat-nginx:
      build:
        context: ./nginx
      container_name: docker-eat-nginx
      restart: always
      tty: true
      volumes:
          - ./eat:/home/www/eat
          - ./nginx/conf.d/eat.conf:/etc/nginx/conf.d/eat.conf
          - ./nginx/log:/data/log/nginx/
      networks:
        web-app-network:
      ports:
        - "80:80"

  docker-eat-go:
      build:
        context: ./eat-go
      container_name: docker-eat-go
      restart: always
      tty: true
      volumes:
        - ./eat-go:/home/www/eat-go
      networks:
        web-app-network:
      ports:
        - "8080:8080"